### ISSUE TITLE
this project need more maintenance 

### ISSUE THREAD

**Issue by marmoure** [louniss/solitaire#1]
the main developer has died from AIDS may  god bless his soul 
we need some one to maintain this

**Comment by louniss** [comment]
Hi, 
i no longer have interest in this project, you can always fork it and derive something from it.
cheers.

**Comment by marmoure** [comment]
yo man been looking for you forever now where did you go
this github was all whats left of you
https://www.facebook.com/profile.php?id=100025858745397
hit me up

**Comment by marmoure** [comment]
where did you go
